steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/tvun-cloudbuild/gcp-cloudrun:$SHORT_SHA', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/tvun-cloudbuild/gcp-cloudrun:$SHORT_SHA']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'cloud-run-test', '--image', 'gcr.io/tvun-cloudbuild/gcp-cloudrun:$SHORT_SHA', '--region', 'us-central1']
images:
- gcr.io/tvun-cloudbuild/gcp-cloudrun:$SHORT_SHA