steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ["build","--network=cloudbuild", "."]
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/staging-env-321815/gcp-cloudrun:$SHORT_SHA', '.']
  timeout: 500s
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/gcr.io/staging-env-321815/gcp-cloudrun:$SHORT_SHA']
