steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--network=cloudbuild','-t', 'gcr.io/tvun-cloudbuild/gcp-cloudrun:$SHORT_SHA', '.']
  timeout: 500s
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/tvun-cloudbuild/gcp-cloudrun:$SHORT_SHA']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', 'cloud-run-test', '--image=gcr.io/tvun-cloudbuild/gcp-cloudrun:$SHORT_SHA', '--region=us-central1']
